import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';

class BoardSquare extends Equatable {
  int id;
  int columnNumber;
  int rowNumber;
  bool hasLabel;
  String rowLabel;
  Widget? occupied;
  Color color;

  BoardSquare({
    required this.id,
    required this.rowNumber,
    required this.columnNumber,
    required this.hasLabel,
    required this.occupied,
    required this.color,
    required this.rowLabel,
  });

  static List<BoardSquare> getBoard(Color _blackColor, Color _whiteColor) => [
        //Row 1
        BoardSquare(
            id: 1,
            rowNumber: 1,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "a1"),
        BoardSquare(
            id: 2,
            rowNumber: 1,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "b1"),
        BoardSquare(
            id: 3,
            rowNumber: 1,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "c1"),
        BoardSquare(
            id: 4,
            rowNumber: 1,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "d1"),
        BoardSquare(
            id: 5,
            rowNumber: 1,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "e1"),
        BoardSquare(
            id: 6,
            rowNumber: 1,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "f1"),
        BoardSquare(
            id: 7,
            rowNumber: 1,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "g1"),
        BoardSquare(
            id: 8,
            rowNumber: 1,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "h1"),

        //Row 2
        BoardSquare(
            id: 9,
            rowNumber: 2,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "a2"),
        BoardSquare(
            id: 10,
            rowNumber: 2,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "b2"),
        BoardSquare(
            id: 11,
            rowNumber: 2,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "c2"),
        BoardSquare(
            id: 12,
            rowNumber: 2,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "d2"),
        BoardSquare(
            id: 13,
            rowNumber: 2,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "e2"),
        BoardSquare(
            id: 14,
            rowNumber: 2,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "f2"),
        BoardSquare(
            id: 15,
            rowNumber: 2,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "g2"),
        BoardSquare(
            id: 16,
            rowNumber: 2,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "h2"),

        //Row 3
        BoardSquare(
            id: 17,
            rowNumber: 3,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "a3"),
        BoardSquare(
            id: 18,
            rowNumber: 3,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "b3"),
        BoardSquare(
            id: 19,
            rowNumber: 3,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "c3"),
        BoardSquare(
            id: 20,
            rowNumber: 3,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "d3"),
        BoardSquare(
            id: 21,
            rowNumber: 3,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "e3"),
        BoardSquare(
            id: 22,
            rowNumber: 3,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "f3"),
        BoardSquare(
            id: 23,
            rowNumber: 3,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "g3"),
        BoardSquare(
            id: 24,
            rowNumber: 3,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "h3"),

        //Row 4
        BoardSquare(
            id: 25,
            rowNumber: 4,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "a4"),
        BoardSquare(
            id: 26,
            rowNumber: 4,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "b4"),
        BoardSquare(
            id: 27,
            rowNumber: 4,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "c4"),
        BoardSquare(
            id: 28,
            rowNumber: 4,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "d4"),
        BoardSquare(
            id: 29,
            rowNumber: 4,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "e4"),
        BoardSquare(
            id: 30,
            rowNumber: 4,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "f4"),
        BoardSquare(
            id: 31,
            rowNumber: 4,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "g4"),
        BoardSquare(
            id: 32,
            rowNumber: 4,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "h4"),

        //Row 5
        BoardSquare(
            id: 33,
            rowNumber: 5,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "a5"),
        BoardSquare(
            id: 34,
            rowNumber: 5,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "b5"),
        BoardSquare(
            id: 35,
            rowNumber: 5,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "c5"),
        BoardSquare(
            id: 36,
            rowNumber: 5,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "d5"),
        BoardSquare(
            id: 37,
            rowNumber: 5,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "e5"),
        BoardSquare(
            id: 38,
            rowNumber: 5,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "f5"),
        BoardSquare(
            id: 39,
            rowNumber: 5,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "g5"),
        BoardSquare(
            id: 40,
            rowNumber: 5,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "h5"),

        //Row 6
        BoardSquare(
            id: 41,
            rowNumber: 6,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "a6"),
        BoardSquare(
            id: 42,
            rowNumber: 6,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "b6"),
        BoardSquare(
            id: 43,
            rowNumber: 6,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "c6"),
        BoardSquare(
            id: 44,
            rowNumber: 6,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "d6"),
        BoardSquare(
            id: 45,
            rowNumber: 6,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "e6"),
        BoardSquare(
            id: 46,
            rowNumber: 6,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "f6"),
        BoardSquare(
            id: 47,
            rowNumber: 6,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "g6"),
        BoardSquare(
            id: 47,
            rowNumber: 6,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "h6"),

        //Row 7
        BoardSquare(
            id: 48,
            rowNumber: 7,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "a7"),
        BoardSquare(
            id: 49,
            rowNumber: 7,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "b7"),
        BoardSquare(
            id: 50,
            rowNumber: 7,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "c7"),
        BoardSquare(
            id: 51,
            rowNumber: 7,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "d7"),
        BoardSquare(
            id: 52,
            rowNumber: 7,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "e7"),
        BoardSquare(
            id: 53,
            rowNumber: 7,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "f7"),
        BoardSquare(
            id: 54,
            rowNumber: 7,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "g7"),
        BoardSquare(
            id: 56,
            rowNumber: 7,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "h7"),

        //Row 8
        BoardSquare(
            id: 57,
            rowNumber: 8,
            columnNumber: 1,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "a8"),
        BoardSquare(
            id: 58,
            rowNumber: 8,
            columnNumber: 2,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "b8"),
        BoardSquare(
            id: 59,
            rowNumber: 8,
            columnNumber: 3,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "c8"),
        BoardSquare(
            id: 60,
            rowNumber: 8,
            columnNumber: 4,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "d8"),
        BoardSquare(
            id: 61,
            rowNumber: 8,
            columnNumber: 5,
            hasLabel: false,
            occupied: null,
            color: _whiteColor,
            rowLabel: "e8"),
        BoardSquare(
            id: 62,
            rowNumber: 8,
            columnNumber: 6,
            hasLabel: false,
            occupied: null,
            color: _blackColor,
            rowLabel: "f8"),
        BoardSquare(
            id: 63,
            rowNumber: 8,
            columnNumber: 7,
            hasLabel: true,
            occupied: null,
            color: _whiteColor,
            rowLabel: "g8"),
        BoardSquare(
            id: 64,
            rowNumber: 8,
            columnNumber: 8,
            hasLabel: true,
            occupied: null,
            color: _blackColor,
            rowLabel: "h8"),
      ];

  @override
  List<Object?> get props => [id, columnNumber, rowNumber, hasLabel, color];
}
